name: demo1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.9  # Updated version

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  get: ^4.6.5  # Added for GetX
  image_picker: ^1.1.2  # Added for Image Picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
  uses-material-design: true